export const MOCK_GIAO_ROWS = [
  {
    id: 1,
    ngayXuatNhap: '28/05/2026',
    maVatTu: 'VIO381007',
    maSAP: 'VIO381007',
    thongSoKyThuat: 'Máy nén khí Airman SDS850S',
    tenVatTu: 'Máy nén khí Airman SDS850S',
    dvt: 'Cái',
    loaiDon: 'Nhập kho',
    maDonNhapKho: 'SGC-STTH_92870_SGC-BCH-CKN_01112',
    maDonXuatKho: 'SGC-STTH_92870_SGC-BCH-CKN_01112',
    khoiLuongNhap: 15.5,
    maDonViGiao: 'SGC-BCH-CKN',
    donViGiao: 'Sông Đà 9',
    nguoiGiao: 'Nguyễn Văn Hùng',
    khoiLuongXuat: null,
    maDonViNhan: '',
    donViNhan: '',
    nguoiPheDuyet: 'Trần Quốc Hoàn',
    tenNguon: 'Kho Tổng SGC',
    maNguon: 'KT-SGC-01',
    lo: 'Lô A1',
    hangMuc: 'Móng hầm',
    soHopDong: 'HĐ-TD/2026/01',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '29C-123.45',
    phanKhu: 'Phân khu A',
    duAn: 'SGC Sunrise Complex',
    tinhTrang: 'NEW',
    nguoiNhan: 'Phạm Minh Chính',
    maDonLienQuan: 'SGC-STTH_92870',
    nhaCungCap: 'Công ty Cổ phần Sông Đà 9',
    maDonChuyenTiepLC: 'LC-99021',
    maDonChuyenTiepNB: 'NB-0129',
    ghiChu: 'Giao hàng đợt 1',
    ghiChuVatTu: 'Kèm theo chứng thư CO/CQ',
    trangThai: 'Đã phê duyệt',
    nhanHieu: 'Airman'
  },
  {
    id: 2,
    ngayXuatNhap: '28/05/2026',
    maVatTu: 'VIO381008',
    maSAP: 'VIO381008',
    thongSoKyThuat: 'Máy nén khí Denyo DIS980SS',
    tenVatTu: 'Máy nén khí Denyo DIS980SS',
    dvt: 'Cái',
    loaiDon: 'Nhập kho',
    maDonNhapKho: 'SGC-STTH_92869_SGC-BCH-CKN_01112',
    maDonXuatKho: 'SGC-STTH_92869_SGC-BCH-CKN_01112',
    khoiLuongNhap: 18.0,
    maDonViGiao: 'SGC-BCH-CKN',
    donViGiao: 'Hòa Phát',
    nguoiGiao: 'Phan Thanh Bình',
    khoiLuongXuat: null,
    maDonViNhan: '',
    donViNhan: '',
    nguoiPheDuyet: 'Lê Hồng Anh',
    tenNguon: 'Kho Tổng SGC',
    maNguon: 'KT-SGC-01',
    lo: 'Lô B1',
    hangMuc: 'Móng hầm',
    soHopDong: 'HĐ-TD/2026/02',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '51D-888.22',
    phanKhu: 'Phân khu A',
    duAn: 'SGC Sunrise Complex',
    tinhTrang: 'NEW',
    nguoiNhan: 'Phạm Minh Chính',
    maDonLienQuan: 'SGC-STTH_92869',
    nhaCungCap: 'Tập đoàn Hòa Phát',
    maDonChuyenTiepLC: 'LC-99022',
    maDonChuyenTiepNB: 'NB-0130',
    ghiChu: 'Giao hàng kèm phụ kiện',
    ghiChuVatTu: 'Màu xanh, sơn chống rỉ',
    trangThai: 'Đã phê duyệt',
    nhanHieu: 'Denyo'
  },
  {
    id: 3,
    ngayXuatNhap: '27/05/2026',
    maVatTu: 'VIO38146',
    maSAP: 'VIO38146',
    thongSoKyThuat: 'Ống vách D900, L=12m',
    tenVatTu: 'Ống vách D900, L=12m',
    dvt: 'ONG',
    loaiDon: 'Nhập kho',
    maDonNhapKho: 'SGC-STTH_92822_SGC-CKN_SGC-BCH-CKN',
    maDonXuatKho: 'SGC-STTH_92822_SGC-CKN_SGC-BCH-CKN',
    khoiLuongNhap: 120.0,
    maDonViGiao: 'SGC-CKN',
    donViGiao: 'Tổng Công Ty Sông Đà',
    nguoiGiao: 'Nguyễn Văn Mạnh',
    khoiLuongXuat: null,
    maDonViNhan: '',
    donViNhan: '',
    nguoiPheDuyet: 'Trần Quốc Hoàn',
    tenNguon: 'Kho Sông Đà',
    maNguon: 'K-SD-02',
    lo: 'Lô C',
    hangMuc: 'Thân thô',
    soHopDong: 'HĐ-TD/2026/05',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '15C-445.67',
    phanKhu: 'Zone 1',
    duAn: 'SGC Golden Tower',
    tinhTrang: 'USED',
    nguoiNhan: 'Nguyễn Hoàng Nam',
    maDonLienQuan: 'SGC-STTH_92822',
    nhaCungCap: 'Tổng Công ty Sông Đà',
    maDonChuyenTiepLC: 'LC-99025',
    maDonChuyenTiepNB: 'NB-0145',
    ghiChu: 'Không phụ kiện kèm theo',
    ghiChuVatTu: 'Mất mác nhẹ bên ngoài',
    trangThai: 'Chờ phê duyệt',
    nhanHieu: 'Hòa Phát'
  },
  {
    id: 4,
    ngayXuatNhap: '27/05/2026',
    maVatTu: 'VIO58570',
    maSAP: 'VIO58570',
    thongSoKyThuat: 'Ống thép đen D113.5x2.0x6m',
    tenVatTu: 'Ống thép đen D113.5',
    dvt: 'Cây',
    loaiDon: 'Nhập kho',
    maDonNhapKho: 'SGC-STTH_92823_SGC-CKN_SGC-BCH-CKN',
    maDonXuatKho: 'SGC-STTH_92823_SGC-CKN_SGC-BCH-CKN',
    khoiLuongNhap: 85.0,
    maDonViGiao: 'SGC-CKN',
    donViGiao: 'Tập đoàn Hòa Phát',
    nguoiGiao: 'Nguyễn Văn Mạnh',
    khoiLuongXuat: null,
    maDonViNhan: '',
    donViNhan: '',
    nguoiPheDuyet: 'Trần Quốc Hoàn',
    tenNguon: 'Kho Sông Đà',
    maNguon: 'K-SD-02',
    lo: 'Lô C',
    hangMuc: 'Thân thô',
    soHopDong: 'HĐ-TD/2026/05',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '15C-445.67',
    phanKhu: 'Zone 1',
    duAn: 'SGC Golden Tower',
    tinhTrang: 'NEW',
    nguoiNhan: 'Nguyễn Hoàng Nam',
    maDonLienQuan: 'SGC-STTH_92823',
    nhaCungCap: 'Thép Hòa Phát',
    maDonChuyenTiepLC: '',
    maDonChuyenTiepNB: '',
    ghiChu: 'Đủ số lượng',
    ghiChuVatTu: 'Bề mặt trơn',
    trangThai: 'Đã phê duyệt',
    nhanHieu: 'Hòa Phát'
  },
  {
    id: 5,
    ngayXuatNhap: '26/05/2026',
    maVatTu: 'VIO00324',
    maSAP: 'VIO00324',
    thongSoKyThuat: 'Ống thép D48 x 6.0m x 1.8mm',
    tenVatTu: 'Ống thép D48',
    dvt: 'CAY',
    loaiDon: 'Nhập kho',
    maDonNhapKho: 'SGC-STTH_92824_SGC-CKN_SGC-BCH-CKN',
    maDonXuatKho: 'SGC-STTH_92824_SGC-CKN_SGC-BCH-CKN',
    khoiLuongNhap: 230.0,
    maDonViGiao: 'SGC-CKN',
    donViGiao: 'Cát Tường',
    nguoiGiao: 'Nguyễn Văn Mạnh',
    khoiLuongXuat: null,
    maDonViNhan: '',
    donViNhan: '',
    nguoiPheDuyet: 'Trần Quốc Hoàn',
    tenNguon: 'Kho Sông Đà',
    maNguon: 'K-SD-02',
    lo: 'Lô D',
    hangMuc: 'Phần hoàn thiện',
    soHopDong: 'HĐ-TD/2026/06',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '29H-556.78',
    phanKhu: 'Zone 2',
    duAn: 'SGC Plaza',
    tinhTrang: 'NEW',
    nguoiNhan: 'Vũ Đức Đam',
    maDonLienQuan: 'SGC-STTH_92824',
    nhaCungCap: 'Thép Cát Tường',
    maDonChuyenTiepLC: '',
    maDonChuyenTiepNB: '',
    ghiChu: 'Không hư hỏng',
    ghiChuVatTu: 'Sơn phủ bảo vệ xanh lam',
    trangThai: 'Từ chối',
    nhanHieu: 'Cát Tường'
  },
  {
    id: 6,
    ngayXuatNhap: '25/05/2026',
    maVatTu: 'VIO3810',
    maSAP: 'VIO22394',
    thongSoKyThuat: 'Khớp nối ben D100',
    tenVatTu: 'Khớp nối ben D100',
    dvt: 'Bộ',
    loaiDon: 'Nhập kho',
    maDonNhapKho: 'SGC-STTH_92825_SGC-CKN_SGC-BCH-CKN',
    maDonXuatKho: 'SGC-STTH_92825_SGC-CKN_SGC-BCH-CKN',
    khoiLuongNhap: 45.0,
    maDonViGiao: 'SGC-CKN',
    donViGiao: 'Hòa Phát',
    nguoiGiao: 'Trần Văn Kiên',
    khoiLuongXuat: null,
    maDonViNhan: '',
    donViNhan: '',
    nguoiPheDuyet: 'Lê Hồng Anh',
    tenNguon: 'Kho Sông Đà',
    maNguon: 'K-SD-02',
    lo: 'Lô E',
    hangMuc: 'Phần kết cấu',
    soHopDong: 'HĐ-TD/2026/07',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '90C-112.34',
    phanKhu: 'Zone 2',
    duAn: 'SGC Plaza',
    tinhTrang: 'NEW',
    nguoiNhan: 'Vũ Đức Đam',
    maDonLienQuan: 'SGC-STTH_92825',
    nhaCungCap: 'Hòa Phát',
    maDonChuyenTiepLC: '',
    maDonChuyenTiepNB: '',
    ghiChu: 'Giao hàng gấp',
    ghiChuVatTu: 'Bọc nilon bảo quản',
    trangThai: 'Chờ phê duyệt',
    nhanHieu: 'Hòa Phát'
  }
];

export const MOCK_NHAN_ROWS = [
  {
    id: 1,
    ngayXuatNhap: '28/05/2026',
    maVatTu: 'VIO38074',
    maSAP: 'VIO38074',
    thongSoKyThuat: 'Khớp nối nhanh Ống ben D100',
    tenVatTu: 'Khớp nối nhanh Ống ben D100',
    dvt: 'Bộ',
    loaiDon: 'Xuất kho',
    maDonNhapKho: '',
    maDonXuatKho: 'SGC-XTH_09234_BCH-SGC-Sunrise',
    khoiLuongNhap: null,
    maDonViGiao: '',
    donViGiao: '',
    nguoiGiao: '',
    khoiLuongXuat: 25.0,
    maDonViNhan: 'SGC-BCH-BTR',
    donViNhan: 'Ban Chỉ Huy SGC Sunrise',
    nguoiPheDuyet: 'Trần Quốc Hoàn',
    tenNguon: 'Kho Tổng SGC',
    maNguon: 'KT-SGC-01',
    lo: 'Lô A2',
    hangMuc: 'Móng hầm',
    soHopDong: 'HĐ-TD/2026/01',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '29C-123.45',
    phanKhu: 'Phân khu A',
    duAn: 'SGC Sunrise Complex',
    tinhTrang: 'USED',
    nguoiNhan: 'Lê Văn Tuyên',
    maDonLienQuan: 'SGC-XTH_09234',
    nhaCungCap: '',
    maDonChuyenTiepLC: 'LC-88123',
    maDonChuyenTiepNB: 'NB-0089',
    ghiChu: 'Chuyển giao công trường',
    ghiChuVatTu: 'Xước bề mặt nhẹ',
    trangThai: 'Đã phê duyệt',
    nhanHieu: 'SGC'
  },
  {
    id: 2,
    ngayXuatNhap: '27/05/2026',
    maVatTu: 'VIO01964',
    maSAP: 'VIO01964',
    thongSoKyThuat: 'Thước dây 100m',
    tenVatTu: 'Thước dây 100m',
    dvt: 'CAI',
    loaiDon: 'Xuất kho',
    maDonNhapKho: '',
    maDonXuatKho: 'SGC-XTH_09235_BCH-SGC-Golden',
    khoiLuongNhap: null,
    maDonViGiao: '',
    donViGiao: '',
    nguoiGiao: '',
    khoiLuongXuat: 10.0,
    maDonViNhan: 'SGC-BCH-GDT',
    donViNhan: 'BCH Golden Tower',
    nguoiPheDuyet: 'Lê Hồng Anh',
    tenNguon: 'Kho Tổng SGC',
    maNguon: 'KT-SGC-01',
    lo: 'Lô B2',
    hangMuc: 'Thân thô',
    soHopDong: 'HĐ-TD/2026/03',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '51D-888.22',
    phanKhu: 'Zone 1',
    duAn: 'SGC Golden Tower',
    tinhTrang: 'NEW',
    nguoiNhan: 'Trương Văn Bảy',
    maDonLienQuan: 'SGC-XTH_09235',
    nhaCungCap: '',
    maDonChuyenTiepLC: 'LC-88124',
    maDonChuyenTiepNB: 'NB-0090',
    ghiChu: 'Dùng cho đo đạc móng nêm',
    ghiChuVatTu: 'Mới nguyên kiện, có bao bọc',
    trangThai: 'Đã phê duyệt',
    nhanHieu: 'KDS Nhật'
  },
  {
    id: 3,
    ngayXuatNhap: '26/05/2026',
    maVatTu: 'VIO03559',
    maSAP: 'VIO03559',
    thongSoKyThuat: 'Đồng hồ đo điện',
    tenVatTu: 'Đồng hồ đo điện',
    dvt: 'Cái',
    loaiDon: 'Xuất kho',
    maDonNhapKho: '',
    maDonXuatKho: 'SGC-XTH_09236_BCH-SGC-Plaza',
    khoiLuongNhap: null,
    maDonViGiao: '',
    donViGiao: '',
    nguoiGiao: '',
    khoiLuongXuat: 5.0,
    maDonViNhan: 'SGC-BCH-PLZ',
    donViNhan: 'BCH SGC Plaza',
    nguoiPheDuyet: 'Trần Quốc Hoàn',
    tenNguon: 'Kho Tổng SGC',
    maNguon: 'KT-SGC-01',
    lo: 'Lô D2',
    hangMuc: 'Trạm biến áp tạm',
    soHopDong: 'HĐ-TD/2026/08',
    thuKho: 'Nguyễn Quốc Tuấn',
    bienSoXe: '90C-112.34',
    phanKhu: 'Zone 2',
    duAn: 'SGC Plaza',
    tinhTrang: 'NEW',
    nguoiNhan: 'Bùi Quang Vinh',
    maDonLienQuan: 'SGC-XTH_09236',
    nhaCungCap: '',
    maDonChuyenTiepLC: '',
    maDonChuyenTiepNB: '',
    ghiChu: 'Kiểm chuẩn kỹ thuật trước khi bàn giao',
    ghiChuVatTu: 'Đầu kim ổn định, pin sạc đẩy đủ',
    trangThai: 'Chờ phê duyệt',
    nhanHieu: 'Sanwa'
  }
];
